[project]
name = "dearfy"
version = "0.1.5a1"
description = "A library for simplifying the creation of complex GUIs using DearPyGUI."
authors = [
    {name = "Romanin", email = "semina054@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "dearpygui>=2.3.1",
    "loguru>=0.7.3",
    "rich>=15.0.0",
    "typing-extensions>=4.16.0",
]

[dependency-groups]
dev = [
    "uv>=0.12.3",
]
